<?php

// Generated by using the "/names" command in irssi
$chan1 = file_get_contents("./logs/compare_1.txt");
$chan2 = file_get_contents("./logs/compare_2.txt");

function processChannel($channel)
{
    $output = [];

    preg_match_all("/\[(.*?)\]/", $channel, $matches);

    foreach($matches[1] as $match)
    {
        $match = preg_replace("/[~&@%+ ]/i", "", $match);

        if($match)
        {
            $output[] = strtolower($match);
        }
    }

    return $output;
}

$chan1_users = processChannel($chan1);
$chan2_users = processChannel($chan2);

print_r(array_intersect($chan1_users, $chan2_users));

?>


