<?php

// Parse IRC network statistics to determine who is missing from a channel
////////////////////////

// Generated by using the "/stats l" command
$rawServer = file_get_contents("./logs/missing_server.txt");

// Generated by using the "/names" command in irssi
$rawChannel = file_get_contents("./logs/missing_channel.txt");

function processServer($server)
{
    $server = explode("\n", $server);
    $output = [];

    foreach($server as $line)
    {
        preg_match("/([a-z][^ ]+?)\[.*?\] [0-9]+ [0-9]+ [0-9]+ [0-9]+ [0-9]+ [0-9]+$/i", $line, $match);

        if(isset($match[1]))
        {
            $output[] = $match[1];
        }
    }

    return $output;
}

function processChannel($channel)
{
    $output = [];
    
    preg_match_all("/\[(.*?)\]/", $channel, $matches);

    foreach($matches[1] as $match)
    {
        $match = preg_replace("/[~&@%+ ]/i", "", $match);

        if($match)
        {
            $output[] = $match;
        }
    }

    return $output;
}

$server = processServer($rawServer);
$channel = processChannel($rawChannel);
$difference = array_diff($server, $channel);

echo "Server names: \n";
print_r($server);
echo "==================================\n";

echo "Channel names: \n";
print_r($channel);
echo "==================================\n";

echo "Difference: \n";
print_r($difference);

?>
