<?php

// This file is generated by running grep on an irssi log:
// grep -E "Day changed|rachel>" irclogs/wetfish/#wetfish.log > rachel.log
$log = file_get_contents("./logs/rachel.log");
$lines = explode("\n", $log);
$days = [];
$currentDay = false;

foreach($lines as $line)
{
    if(preg_match("/^--- Day changed (.*)$/", $line, $match))
    {
        $currentDay = $match[1];
    }
    else
    {
        if($currentDay)
        {
            $days[$currentDay]++;
        }
    }
}

print_r($days);

?>
